<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Landis.Extension.Insects</RootNamespace>
    <AssemblyCompany>Landis-II-Foundation</AssemblyCompany>
    <AssemblyCopyright>Landis-II-Foundation</AssemblyCopyright>
    <AssemblyName>Landis.Extension.BiomassInsects-v4</AssemblyName>
    <AssemblyVersion>4.0</AssemblyVersion>
    <FileVersion>4.0</FileVersion>
    <Version>4.0</Version>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PackageReleaseNotes>.NET Standard 2.0 update</PackageReleaseNotes>
    <AssemblyProduct>Landis.Extension.BiomassBDA-v2</AssemblyProduct>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RepositoryUrl>https://github.com/LANDIS-II-Foundation/Extension-Biomass-Insects</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>English</NeutralLanguage>
    <Authors>Landis-II-Foundation</Authors>
    <Copyright>Landis-II-Foundation</Copyright>
    <PackageTags>LANDIS-II;Landis;Extension;Biomass BDA</PackageTags>
    <PackageLicenseUrl>https://github.com/LANDIS-II-Foundation/Extension-Biomass-Insects/blob/master/LICENSE.md</PackageLicenseUrl>
    <PackageProjectUrl>http://www.landis-ii.org</PackageProjectUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
</PropertyGroup>
  

  <ItemGroup>
    <PackageReference Include="Landis.Core" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Landis.Library.UniversalCohorts-v1">
    </Reference>
    <Reference Include="Landis.Library.Metadata-v2">
    </Reference>
  </ItemGroup>

</Project>
